package com.topsoutherncoders.demoapp;

import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouterLayout;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.vaadin.firitin.appframework.MainLayout;

@SpringBootApplication
public class DemoAppApplication {

	// In MainView and AnotherView, replace RouterLayoutView
	// with ChromeWithAutogeneratedMenuView for a different implementation
	@Route(value = "main", layout = RouterLayoutView.class)
	public static class MainView extends VerticalLayout {
		public MainView() {
			add(
					new H1("This is the your main view.")
					);
		}
	}

	@Route(value = "anotherview", layout = RouterLayoutView.class)
	public static class AnotherView extends VerticalLayout {
		public AnotherView() {
			add(
					new H1("This is another of your views")
					);
		}
	}

	public static class RouterLayoutView extends VerticalLayout implements RouterLayout {
		public RouterLayoutView() {
			add("This is a header for all views using this layout");
		}
	}

	// Viritin MainLayout uses the standard AppLayout but automatically
	// generates the menu of available Route annotations, configurable with annotations
	public static class ChromeWithAutogeneratedMenu extends MainLayout {
		@Override
		protected String getDrawerHeader() {
			return null;
		}
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoAppApplication.class, args);
	}
}
